#!/bin/csh -f

# using this to verify that the package installs aren't whacking ownership
# or permissions on any directories they shouldn't be touching

foreach f (`lsbom -d -p f $1/Contents/*.bom`)
  (cd / ; ls -ld $f | awk '{print $1" "$3" "$4" "$9}')
end

